version: '3.9'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: yourname_fdtest
  ports: ["5432:5432"]
redis:
  image: redis:7
  ports: ["6379:6379"]
api:
  build:
    context: ../
    dockerfile: docker/api.Dockerfile
  env_file: ../.env
  depends_on: [db, redis]
  ports: ["4000:4000"]
web:
  build:
    context: ../
    dockerfile: docker/web.Dockerfile
  env_file: ../.env
  depends_on: [api]
  ports: ["3000:3000"]